API-based webapp
danutibe07/Javasript-Capstone-Project pull request #27
Opened 2023-03-24 22:05 UTC by danutibe07

An API web app that displays data about different series.
- [ ] Send and receive data from an API.
- [ ] Used webpack to build and start the app.
- [ ] Made use of callbacks and promises.
- [ ] Wrote unit tests to cover every aspect of the app.

2023-03-24 22:36 UTC, VICTOR-CHUKWU requested changes
Hi @danutibe07  and @Kaghenimbale  and @Rana-Mudassir , 
## STATUS: CHANGES REQUIRED :recycle: 
Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-24 22:36 UTC, VICTOR-CHUKWU commented on test/api.test.js
> +});
- [ ] some of your tests are failing kindly fix this
![image](https://user-images.githubusercontent.com/66097371/227654025-85c76036-4d58-449f-add2-9a731ca9c9a3.png)

2023-03-24 22:36 UTC, VICTOR-CHUKWU commented on src/module/displaySeries.js
> +// }
- [ ] kindly remove comments from your code base

2023-03-24 22:36 UTC, VICTOR-CHUKWU commented on src/index.html
> +      </nav>
- [ ] there  should be counter present in the home page that show the number of items

2023-03-25 00:13 UTC, huseyinbiyik approved these changes
Hi team

## ✔️ Status: APPROVED 🏆 🎉 🎊

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/wZjlCH43M3M0U/giphy.gif)



## Highlights
- Linter set up well and checks pass 🟢
- Git flow followed 👌
- PR description is descriptive 📝
- Great implementation of the requested changes of previous reviewers 🕸️

## Optional suggestions
- Your files are not organized, tests and modules are located in different folders. Kindly organize your folder system to have a professional repository 👍 
-  Please make sure your commit messages have imperative tense. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML" 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 00:13 UTC, huseyinbiyik commented on src/module/CommentTest/getComment.test.js
> +/**
[OPTIONAL] Unfortunately, your tests were not built properly. You should write tests for the counter functions. But you are creating some functions and testing them which is not useful for testing the functionality of the app. 
<img width="1072" alt="Screenshot 2023-03-25 at 2 56 22 AM" src="https://user-images.githubusercontent.com/25887253/227664534-59265fda-26e7-41d5-80a2-dc1f36af3ffc.png">

2023-03-25 05:05 UTC, merged